#!/bin/bash
# na podstawie:
# http://blog.oddbit.com/2014/08/11/four-ways-to-connect-a-docker/
set -u
set -e
set +x

# $1 - nazwa kontenera
# $2 - żądany IP (ostatni człon)

container_pid=$(docker-pid $1)
container_ifn="vif$2"   # nazwa wirtualnego IF kontenera

# ens2 - IF gospodarza dockerów (VM) do którgo linkujemy vifXXX
# 192.168.123.XXX - IP, pod którym kontener ma być widoczny w podsieci ($2)
# 192.168.123.1 - brama podsieci
# powyższe ważne dla mojej podsieci VM (qemu/kvm)
# docker-pid to skrypt bash-a

container_pid=$(docker-pid $1)
container_ifn="vif$2"   # container interface name

cmd="ip link add $container_ifn link ens2 type macvlan mode bridge"
echo $cmd
eval "$cmd"

cmd="ip link set netns $container_pid $container_ifn"
echo $cmd
eval "$cmd"

cmd="nsenter -t $container_pid -n ip link set $container_ifn up"
echo $cmd
eval "$cmd"

cmd="nsenter -t $container_pid -n ip route del default"
echo $cmd
eval "$cmd"

cmd="nsenter -t $container_pid -n ip addr add 192.168.123.$2/24 dev $container_ifn"
echo $cmd
eval "$cmd"

cmd="nsenter -t $container_pid -n ip route add default via 192.168.123.1 dev $container_ifn"
echo $cmd
eval "$cmd"

exit 0
