#!/bin/bash
set -u
set -e
set -x

# $1 - nazwa kontenera

docker run \
    --name=$1 \
    --hostname=$1 \
    --detach \
    --volume=/media-storage:/media-storage \
    --volume=/my-media/$1:/my-media \
    debian:egp

echo "Na wszelki wypadek czekam sekundę ..."
sleep 1
/usr/local/sbin/mvlan $1
